[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "UNAL-DNIL Módulo Web Convocatorias"
authors = [{name = "David Toro Triana", email = "dtorot@opensai.org"}]
dynamic = ["version", "description"]
